// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWgIiUJ2OTcWY5cm_9nAP0UUocyrmtMTs',
    appId: '1:913694415043:web:69974b8c74fc346841ea76',
    messagingSenderId: '913694415043',
    projectId: 'stoore-f18ae',
    authDomain: 'stoore-f18ae.firebaseapp.com',
    storageBucket: 'stoore-f18ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxuf3BYO_oMWIDSskKOU8omBDCI_hAeQ4',
    appId: '1:913694415043:android:cf5a9ff2fdf822cf41ea76',
    messagingSenderId: '913694415043',
    projectId: 'stoore-f18ae',
    storageBucket: 'stoore-f18ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMD5JSXwZXmebMj6e9TvkwGUldkoOVjZY',
    appId: '1:913694415043:ios:05010112ff812e7341ea76',
    messagingSenderId: '913694415043',
    projectId: 'stoore-f18ae',
    storageBucket: 'stoore-f18ae.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMD5JSXwZXmebMj6e9TvkwGUldkoOVjZY',
    appId: '1:913694415043:ios:05010112ff812e7341ea76',
    messagingSenderId: '913694415043',
    projectId: 'stoore-f18ae',
    storageBucket: 'stoore-f18ae.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWgIiUJ2OTcWY5cm_9nAP0UUocyrmtMTs',
    appId: '1:913694415043:web:a727bb42ce2b17ae41ea76',
    messagingSenderId: '913694415043',
    projectId: 'stoore-f18ae',
    authDomain: 'stoore-f18ae.firebaseapp.com',
    storageBucket: 'stoore-f18ae.firebasestorage.app',
  );
}
